name: Pulumi

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh
      
      - name: Install AWS CLI
        run: sudo apt update && sudo apt install awscli -y
      
      - name: AWS EKS
        run: |          
          mkdir -p ~/.kube
          sudo chown -R :users ~/.kube
          aws eks --region us-east-1 update-kubeconfig --name ever-dev
          kubectl get svc
        env:  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          KUBECONFIG: /home/runner/.kube/config-ever-dev
      
      - name: Stacks
        run: ~/.pulumi/bin/pulumi stack ls
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Install NodeJS and dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install

      - name: Dev Stack
        run: ~/.pulumi/bin/pulumi up --yes --stack dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          EVER_KUBECONFIG: true
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_MODE: ${{ secrets.DB_MODE }}
          KUBECONFIG: /home/runner/.kube/config-ever-dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ZONE_ID_DEV: ${{ secrets.CLOUDFLARE_ZONE_ID_DEV }}
          ZONE_ID_PROD: ${{ secrets.CLOUDFLARE_ZONE_ID_PROD }}

      - name: Demo Stack
        run: ~/.pulumi/bin/pulumi up --yes --stack demo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          EVER_KUBECONFIG: true
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_MODE: ${{ secrets.DB_MODE }}
          KUBECONFIG: /home/runner/.kube/config-ever-dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ZONE_ID_DEV: ${{ secrets.CLOUDFLARE_ZONE_ID_DEV }}
          ZONE_ID_PROD: ${{ secrets.CLOUDFLARE_ZONE_ID_PROD }}

      - name: Production Stack
        run: ~/.pulumi/bin/pulumi up --yes --stack prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          EVER_KUBECONFIG: true
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_MODE: ${{ secrets.DB_MODE }}
          KUBECONFIG: /home/runner/.kube/config-ever-dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ZONE_ID_DEV: ${{ secrets.CLOUDFLARE_ZONE_ID_DEV }}
          ZONE_ID_PROD: ${{ secrets.CLOUDFLARE_ZONE_ID_PROD }}
